[package]
name = "btoprs"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "A dependency-free terminal resource monitor"
readme = "README.md"
homepage = "https://github.com/EriksRemess/btop-rust"
repository = "https://github.com/EriksRemess/btop-rust"

[[bin]]
name = "btoprs"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
