# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#1e1e2e"

# Main text color
theme[main_fg]="#cdd6f4"

# Title color for boxes
theme[title]="#cdd6f4"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#89b4fa"

# Background color of selected item in processes box
theme[selected_bg]="#f38ba8"

# Foreground color of selected item in processes box
theme[selected_fg]="#cdd6f4"

# Color of inactive/disabled text
theme[inactive_fg]="#6c7086"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#cdd6f4"

# Background color of the percentage meters
theme[meter_bg]="#585b70"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#cba6f7"

# Cpu box outline color
theme[cpu_box]="#cba6f7"

# Memory/disks box outline color
theme[mem_box]="#a6e3a1"

# Net up/down box outline color
theme[net_box]="#f38ba8"

# Processes box outline color
theme[proc_box]="#89b4fa"

# Box divider line and small boxes line color
theme[div_line]="#6c7086"

# Temperature graph colors
theme[temp_start]="#cba6f7"
theme[temp_mid]="#f5c2e7"
theme[temp_end]="#f38ba8"

# CPU graph colors
theme[cpu_start]="#cba6f7"
theme[cpu_mid]="#89b4fa"
theme[cpu_end]="#a6e3a1"

# Mem/Disk free meter
theme[free_start]="#fab387"
theme[free_mid]="#f9e2af"
theme[free_end]="#f38ba8"

# Mem/Disk cached meter
theme[cached_start]="#94e2d5"
theme[cached_mid]="#89b4fa"
theme[cached_end]="#74c7ec"

# Mem/Disk available meter
theme[available_start]="#fab387"
theme[available_mid]="#f9e2af"
theme[available_end]="#fab387"

# Mem/Disk used meter
theme[used_start]="#a6e3a1"
theme[used_mid]="#8bd5a6"
theme[used_end]="#53c68c"

# Download graph colors
theme[download_start]="#cba6f7"
theme[download_mid]="#a6e3a1"
theme[download_end]="#89b4fa"

# Upload graph colors
theme[upload_start]="#cba6f7"
theme[upload_mid]="#f5c2e7"
theme[upload_end]="#f38ba8"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#a6e3a1"
theme[process_mid]="#94e2d5"
theme[process_end]="#89b4fa"
